version: 2.1

orbs:
  browserstack: browserstack/selenium@1.5.0

jobs:
  build:
    executor: browserstack/default
    steps:
      - checkout
      - browserstack/install
      - run:
          name: Run tests on BrowserStack
          command: |
            mvn clean test -Dsurefire.suiteXmlFiles=src/test/resources/testng.xml -Dbrowserstack.username=$BROWSERSTACK_USERNAME -Dbrowserstack.accessKey=$BROWSERSTACK_ACCESS_KEY -Dbrowserstack.appiumVersion=1.21.0 -Dbrowserstack.device=Google Pixel 4 -Dbrowserstack.os.version=11.0
