version: 2
jobs:
  build:
    working_directory: ~/mobile-automation-project
    docker:
      - image: circleci/android:api-30
    environment:
      ANDROID_HOME: /Users/USEr/AppData/Local/Android/Sdk
      PATH: $PATH:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: 
          name: Start appium server
          command: appium &
      - run: adb devices
      - run: adb install -r app/build/outputs/apk/debug/app-release.apk
      - run: .mvn test

